[server]
port = 8501
headless = true
enableXsrfProtection = true

[theme]
primaryColor = "#FF002A"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D23"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false
